const CATEGORIES = {
  peinture: { label: "Peinture", color: "#c99a2e" },
  cinema: { label: "Cinéma & séries", color: "#c1443c" },
  musique: { label: "Musique", color: "#7452b8" },
};

const WORKS = [
  // --- PEINTURE : la vallée de l'Oise, berceau de l'impressionnisme ---
  {
    id: "vangogh-eglise",
    category: "peinture",
    title: "L’Église d’Auvers-sur-Oise",
    author: "Vincent van Gogh",
    year: "1890",
    place: "Auvers-sur-Oise",
    lat: 49.0733,
    lng: 2.1698,
    summary: "Peinte durant les deux derniers mois de la vie de Van Gogh à Auvers-sur-Oise, cette toile est aujourd’hui l’une des pièces maîtresses des collections du musée d’Orsay.",
    location: "Conservée au musée d’Orsay, Paris",
    source: "https://www.musee-orsay.fr",
  },
  {
    id: "vangogh-corbeaux",
    category: "peinture",
    title: "Champ de blé aux corbeaux",
    author: "Vincent van Gogh",
    year: "1890",
    place: "Auvers-sur-Oise",
    lat: 49.0755,
    lng: 2.1780,
    summary: "Peinte en juillet 1890 dans les champs de blé au-dessus du village, cette toile au format allongé et au ciel tourmenté compte parmi les toutes dernières œuvres du peintre.",
    location: "Van Gogh Museum, Amsterdam",
    source: "https://www.van-gogh.fr/les-70-toiles-d-auvers-sur-oise.php",
  },
  {
    id: "vangogh-gachet",
    category: "peinture",
    title: "Portrait du docteur Gachet",
    author: "Vincent van Gogh",
    year: "1890",
    place: "Auvers-sur-Oise",
    lat: 49.0728,
    lng: 2.1706,
    summary: "Portrait du médecin auversois qui suivit Van Gogh durant son séjour, l’un des 74 tableaux peints par l’artiste en deux mois à Auvers-sur-Oise.",
    location: "Collection privée",
    source: "https://www.van-gogh.fr/les-70-toiles-d-auvers-sur-oise.php",
  },
  {
    id: "cezanne-pendu",
    category: "peinture",
    title: "La Maison du pendu à Auvers-sur-Oise",
    author: "Paul Cézanne",
    year: "1873",
    place: "Auvers-sur-Oise",
    lat: 49.0733,
    lng: 2.1698,
    summary: "Cézanne s’installe d’abord à Saint-Ouen-l’Aumône avant de rejoindre Auvers-sur-Oise en 1872 sur les conseils du docteur Gachet. Cette toile marque le tournant impressionniste de sa peinture.",
    location: "Conservée au musée d’Orsay, Paris",
    source: "https://www.musee-orsay.fr",
  },
  {
    id: "daubigny-atelier",
    category: "peinture",
    title: "Maison-atelier de Daubigny",
    author: "Charles-François Daubigny",
    year: "à partir de 1860",
    place: "Auvers-sur-Oise",
    lat: 49.0740,
    lng: 2.1690,
    summary: "Précurseur des impressionnistes et source d’inspiration pour Van Gogh, Daubigny installe à Auvers une maison-atelier dont les décors peints associent son fils, Corot, Daumier et Oudinot.",
    location: "Maison-atelier Daubigny, ouverte à la visite",
    source: "https://www.van-gogh.fr/auvers-parcours-des-impressionnistes.php",
  },
  {
    id: "pissarro-pontoise",
    category: "peinture",
    title: "Les toiles pontoisiennes de Pissarro",
    author: "Camille Pissarro",
    year: "1866–1869 puis 1872–1882",
    place: "Pontoise",
    lat: 49.0505,
    lng: 2.1027,
    summary: "Pissarro vécut à Pontoise pendant près de quinze ans au total et y peignit un grand nombre de vues de la ville, des coteaux et de l’Oise, faisant de Pontoise l’un des foyers de l’impressionnisme naissant.",
    location: "Musée Pissarro, Pontoise",
    source: "https://ville-pontoise.fr/pontoise-la-ville-des-impressionnistes",
  },

  // --- CINÉMA & SÉRIES ---
  {
    id: "film-mome",
    category: "cinema",
    title: "La Môme (La Vie en rose)",
    year: "2007",
    place: "Pontoise",
    lat: 49.0512,
    lng: 2.1032,
    summary: "Le biopic d’Édith Piaf réalisé par Olivier Dahan a tourné une scène place de la Harengerie, dans le centre historique de Pontoise.",
    location: "Place de la Harengerie, Pontoise",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-long-dimanche",
    category: "cinema",
    title: "Un long dimanche de fiançailles",
    year: "2004",
    place: "Auvers-sur-Oise",
    lat: 49.0705,
    lng: 2.1735,
    summary: "Le film de Jean-Pierre Jeunet avec Audrey Tautou a utilisé l’auberge Ravoux, l’auberge où vécut et mourut Van Gogh, comme décor de tournage.",
    location: "Auberge Ravoux, Auvers-sur-Oise",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-rabbi-jacob",
    category: "cinema",
    title: "Les Aventures de Rabbi Jacob",
    year: "1973",
    place: "Goussainville",
    lat: 49.0186,
    lng: 2.4736,
    summary: "Le classique de Gérard Oury avec Louis de Funès a tourné une partie de ses scènes dans l’ancienne distillerie de Goussainville.",
    location: "Ancienne distillerie, Goussainville",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-rush-hour",
    category: "cinema",
    title: "Rush Hour 3",
    year: "2007",
    place: "Roissy-en-France",
    lat: 49.0097,
    lng: 2.5479,
    summary: "Des scènes de la comédie policière avec Jackie Chan et Chris Tucker ont été tournées à l’aéroport Roissy-Charles-de-Gaulle.",
    location: "Aéroport Roissy-Charles-de-Gaulle",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-moliere",
    category: "cinema",
    title: "Molière",
    year: "2007",
    place: "Ambleville",
    lat: 49.1878,
    lng: 1.7581,
    summary: "Le film de Laurent Tirard avec Romain Duris a utilisé le château d’Ambleville, dans le Vexin français, comme un de ses décors.",
    location: "Château d’Ambleville",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-perles-couronne",
    category: "cinema",
    title: "Les Perles de la couronne",
    year: "1937",
    place: "Asnières-sur-Oise",
    lat: 49.1497,
    lng: 2.3711,
    summary: "Ce classique de Sacha Guitry et Christian-Jaque a tourné à l’abbaye de Royaumont, l’une des plus grandes abbayes cisterciennes de France.",
    location: "Abbaye de Royaumont, Asnières-sur-Oise",
    source: "https://www.tom.travel/2020/11/20/7-films-qui-ont-ete-tournes-dans-le-val-doise/",
  },
  {
    id: "film-mousquetaires",
    category: "cinema",
    title: "Les Trois Mousquetaires",
    year: "2023",
    place: "Mériel",
    lat: 49.0928,
    lng: 2.1719,
    summary: "Le diptyque avec François Civil, Romain Duris et Eva Green a tourné à l’abbaye Notre-Dame-du-Val de Mériel.",
    location: "Abbaye Notre-Dame-du-Val, Mériel",
    source: "https://www.valdoise.fr/actualite/1156/175-le-val-d-oise-est-une-terre-de-cinema.htm",
  },
  {
    id: "serie-walking-dead",
    category: "cinema",
    title: "The Walking Dead (spin-off)",
    year: "2022",
    place: "Asnières-sur-Oise",
    lat: 49.1497,
    lng: 2.3711,
    summary: "Une équipe de tournage américaine avec Norman Reedus a posé ses caméras à l’abbaye de Royaumont et à Menouville pour un spin-off de la série.",
    location: "Abbaye de Royaumont & Menouville",
    source: "https://www.valdoise.fr/actualite/1156/175-le-val-d-oise-est-une-terre-de-cinema.htm",
  },
  {
    id: "serie-newlook",
    category: "cinema",
    title: "The New Look",
    year: "2022",
    place: "Le Vexin français",
    lat: 49.1075,
    lng: 1.9942,
    summary: "La série Apple TV+ sur Christian Dior et Coco Chanel, avec Juliette Binoche et John Malkovich, a tourné plusieurs scènes dans le Vexin français.",
    location: "Le Vexin français",
    source: "https://www.valdoise.fr/actualite/1156/175-le-val-d-oise-est-une-terre-de-cinema.htm",
  },

  // --- MUSIQUE ---
  {
    id: "musique-ministere-amer",
    category: "musique",
    title: "Ministère AMER",
    author: "Passi & Stomy Bugsy",
    year: "années 1990",
    place: "Sarcelles",
    lat: 48.9964,
    lng: 2.3789,
    summary: "Duo fondateur du rap français originaire de Sarcelles, à l’origine du collectif Secteur Ä qui a marqué toute une scène hip-hop val-d’oisienne.",
    location: "Sarcelles",
    source: "https://en.wikipedia.org/wiki/Minist%C3%A8re_AMER",
  },
  {
    id: "musique-secteur-a",
    category: "musique",
    title: "Secteur Ä",
    year: "années 1990",
    place: "Garges-lès-Gonesse",
    lat: 48.9744,
    lng: 2.3956,
    summary: "Collectif de rap réunissant des artistes de Garges-lès-Gonesse, Sarcelles et Villiers-le-Bel, fondé par le Ministère AMER : une des scènes fondatrices du rap français des années 1990.",
    location: "Garges-lès-Gonesse · Sarcelles · Villiers-le-Bel",
    source: "https://fr.wikipedia.org/wiki/Secteur_%C3%84",
  },
  {
    id: "musique-osfa",
    category: "musique",
    title: "O.S.F.A",
    year: "depuis 1993",
    place: "Argenteuil",
    lat: 48.9478,
    lng: 2.2469,
    summary: "Groupe de hip-hop fondé à Argenteuil en 1993, composé d’Alonzoo, Mic Fury et Horseck.",
    location: "Argenteuil",
    source: "https://www.perceptum.fr/nouvelle-generation-rap-du-val-doise-95-sounds-en-premiere-ligne/",
  },
  {
    id: "musique-relic",
    category: "musique",
    title: "Relic",
    year: "depuis 1996",
    place: "Argenteuil",
    lat: 48.9478,
    lng: 2.2469,
    summary: "Groupe de hip-hop originaire d’Argenteuil, formé en 1996, représentatif de la scène rap de la ville dans les années 1990-2000.",
    location: "Argenteuil",
    source: "https://www.perceptum.fr/nouvelle-generation-rap-du-val-doise-95-sounds-en-premiere-ligne/",
  },
  {
    id: "musique-kaaris",
    category: "musique",
    title: "Kaaris",
    year: "grandit à partir de 1986",
    place: "Taverny",
    lat: 49.0367,
    lng: 2.2158,
    summary: "Né à Abidjan, Kaaris grandit à partir de six ans à Taverny avant de déménager en Seine-Saint-Denis. Il devient l’un des artistes qui a popularisé la trap en France.",
    location: "Taverny",
    source: "https://hiphopcorner.fr/member/kaaris/",
  },
];
